
theme = "github_dark"

[editor]
line-number = "relative"
bufferline = "always"
cursorline = true
color-modes = true
true-color = true

[editor.file-picker]
hidden = false
git-ignore = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.lsp]
auto-signature-help = false
display-messages = true
display-inlay-hints = false

[editor.statusline]
left = ["mode", "file-type",  "file-encoding" , "version-control"] 
center = ["spinner","file-name", "file-modification-indicator"]
right = [
    "selections",
    "primary-selection-length",
    "position",
    "total-line-numbers",
    "spacer",
    "diagnostics",
    "workspace-diagnostics",
]
separator = "|"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = "extend_line_above"

[keys.normal.space]
w = ":write"
q = ":buffer-close"
Q = ":buffer-close-others"
"=" = ":reflow 80"

[keys.insert]
C-space = "completion"

