# Language servers

[language-server.tailwindcss]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.eslint.config]
format = true
nodePath = ""
onIgnoredFiles = "off"
packageManager = "yarn"
quiet = false
rulesCustomizations = []
run = "onType"
useESLintClass = false
validate = "on"
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
codeActionOnSave = { mode = "all" }
experimental = {}
problems = { shortenToSingleLine = false }
workingDirectory = { mode = "auto" }

[language-server.vscode-json-language-server.config]
json = { validate = { enable = true }, format = { enable = true } }
provideFormatter = true


[language-server.vscode-css-language-server.config]
css = { validate = { enable = true } }
scss = { validate = { enable = true } }
less = { validate = { enable = true } }
provideFormatter = true

# Languages

[[language]]
name = "svelte"
auto-format = true
language-servers = [
  { name = "tailwindcss", except-features = ["hover"] },
  "svelteserver",
  "eslint",
]
formatter = { command = "prettier", args = ["--parser", "svelte"] }

[[language]]
name = "typescript"
auto-format = true
language-servers = [
  { name = "tailwindcss", except-features = ["hover"] },
  "typescript-language-server",
  "eslint",
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "javascript"
auto-format = true
language-servers = [
  { name = "tailwindcss", except-features = ["hover"] },
  "typescript-language-server",
  "eslint",
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "html"
auto-format = true
language-servers = [
  "tailwindcss",
  "vscode-html-language-server",
  "eslint",
]
formatter = { command = "prettier", args = ["--parser", "html"] }

[[language]]
name = "css"
auto-format = true
language-servers = [
  { name = "tailwindcss", except-features = ["hover"] },
  "vscode-css-language-server",
  "eslint",
]
formatter = { command = "prettier", args = ["--parser", "css"] }

[[language]]
name = "scss"
auto-format = true
language-servers = [
  { name = "tailwindcss", except-features = ["hover"] },
  "vscode-css-language-server",
  "eslint",
]
formatter = { command = "prettier", args = ["--parser", "scss"] }

[[language]]
name = "json"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "json"] }

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "yaml"] }

